### ISSUE TITLE
Update the Pymongo dependency

### ISSUE THREAD

**Issue by feanil** [openedx/opaque-keys#311]
The pymongo dependency is pinned to an old version in `base.in`.  Update the pin, update the output `.txt` files and fix any tests that break.

Newer versions may have breaking changes that may break upstream edx-platform so we should make sure to upgrade opaque keys and pymongo in edx-platform and fix any issues we encounter there as well as a part of this ticket.

**Comment by feanil** [comment]
FYI, the BOM team might be picking this up so coordinate with them if you're gonna be working on it.

**Comment by feanil** [comment]
Related edx-platform ticket that should be updated/closed when edx-platform is up-to-date: https://github.com/openedx/edx-platform/issues/34586

**Comment by irtazaakram** [comment]
BOM squad is working on upgrading pymongo ref: https://github.com/openedx/edx-platform/pull/34675

**Comment by farhan** [comment]
@feanil Please close it has PR has been merged.
